### PR TITLE
Add badges for number of jobs and released files for a given workspace

### PR DESCRIPTION
**Pull request by ghickman**
This adds a couple of extra badges and reorganises the badge views into their own module.

Refs #1968

### CODE REVIEW

**Review by bloodearnest — COMMENTED** [review]
I'm not sure the url requirements work here.

Currently, this would require the urls in the README to have explicit org, project, and workspace in order to work.

At the point of generating the initial README, we don't know all that. Indeed, job-server doesn't even know that yet, as the repo has to exist before such things can be determined. That means for these badges to be useful, a user would have to manually edit and commit the readme to supply the missing information.


When we generate, the initial README, we do know the name of the repo, we could include that in the badge url, e.g.

`https://jobs.opensafely.org/badges/opensafely/foo/$BADGETYPE`

Now we can render a badge based on the workspaces linked to the repo.

We don't know the branch however, which affects workspace currently (another reason to bad multiple branches!), and the branch of course can change.

However, we could maybe hack around this by using `referer`, which in the case of viewing a readme in a branch would look like:

`https://github.com/openafely/foo/tree/branch`

Then the badge url could use this info to pick the write workspace to use in the case of multiple workspaces.

**Comment by ghickman** [comment]
It seems like we're not [the first to think of the referrer](https://github.com/github/markup/issues/1072), unfortunately GitHub has yet to implement anything that would help us there.

I don't see a way forward for this change now.  If we merge as is then the readme can't include badges to start with and if we include them for only workspaces pointing at `main` then any workspaces for a branch are showing incorrect data.

I'm going to close this PR because we need to make a call on how we update readmes before we can add badges.

**Comment by bloodearnest** [comment]
I checked manually, and my browser does send a referer header that would be enough

**Comment by ghickman** [comment]
I tested locally with ngrok and didn't get a referer header for the badge URL.  Did you check the request made for an image link in a markdown file?

**Comment by bloodearnest** [comment]
Looks like I tested the wrong thing, sorry.

So supporting auto updating badges by default is tricker when there multiple workspaces (another reason to ban them)

We could show total jobs/released/published for all workspaces for this repo. That will still be live.
 
And if there is >1 workspace for a repo, could we link to a (new?) page that let you choose the workspace?

**Pull request closed without merging**
